FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# Build-time env vars — passed via docker-compose build.args (sourced from secrets file).
# VITE_* vars are inlined into the JS bundle at build time; they must arrive as ARGs.
ARG VITE_APPWRITE_ENDPOINT
ARG VITE_APPWRITE_PROJECT_ID
ARG VITE_APPWRITE_DATABASE_ID
ARG VITE_APPWRITE_COLLECTION_TRIPS
ARG VITE_APPWRITE_COLLECTION_TRIP_STOPS
ARG VITE_APPWRITE_COLLECTION_BOOKINGS
ARG VITE_APPWRITE_COLLECTION_USER_ROLES
ARG VITE_APPWRITE_COLLECTION_PRICING_RULES
ARG VITE_APPWRITE_COLLECTION_PROFILES
ARG VITE_APPWRITE_COLLECTION_DRIVERS
ARG VITE_APPWRITE_COLLECTION_VEHICLES
ARG VITE_APPWRITE_COLLECTION_TRIP_SEAT_RESERVATIONS
ARG VITE_APPWRITE_DRIVER_DOCS_BUCKET_ID
ARG VITE_APPWRITE_COLLECTION_HERO_BANNERS
ARG VITE_APPWRITE_BANNERS_BUCKET_ID
ARG VITE_GOOGLE_MAPS_API_KEY
ARG VITE_APPWRITE_COLLECTION_BANK_ACCOUNTS
ARG VITE_APPWRITE_COLLECTION_PAYOUT_REQUESTS

# Promote ARGs to ENV so Vite picks them up during npm run build
ENV VITE_APPWRITE_ENDPOINT=$VITE_APPWRITE_ENDPOINT
ENV VITE_APPWRITE_PROJECT_ID=$VITE_APPWRITE_PROJECT_ID
ENV VITE_APPWRITE_DATABASE_ID=$VITE_APPWRITE_DATABASE_ID
ENV VITE_APPWRITE_COLLECTION_TRIPS=$VITE_APPWRITE_COLLECTION_TRIPS
ENV VITE_APPWRITE_COLLECTION_TRIP_STOPS=$VITE_APPWRITE_COLLECTION_TRIP_STOPS
ENV VITE_APPWRITE_COLLECTION_BOOKINGS=$VITE_APPWRITE_COLLECTION_BOOKINGS
ENV VITE_APPWRITE_COLLECTION_USER_ROLES=$VITE_APPWRITE_COLLECTION_USER_ROLES
ENV VITE_APPWRITE_COLLECTION_PRICING_RULES=$VITE_APPWRITE_COLLECTION_PRICING_RULES
ENV VITE_APPWRITE_COLLECTION_PROFILES=$VITE_APPWRITE_COLLECTION_PROFILES
ENV VITE_APPWRITE_COLLECTION_DRIVERS=$VITE_APPWRITE_COLLECTION_DRIVERS
ENV VITE_APPWRITE_COLLECTION_VEHICLES=$VITE_APPWRITE_COLLECTION_VEHICLES
ENV VITE_APPWRITE_COLLECTION_TRIP_SEAT_RESERVATIONS=$VITE_APPWRITE_COLLECTION_TRIP_SEAT_RESERVATIONS
ENV VITE_APPWRITE_DRIVER_DOCS_BUCKET_ID=$VITE_APPWRITE_DRIVER_DOCS_BUCKET_ID
ENV VITE_APPWRITE_COLLECTION_HERO_BANNERS=$VITE_APPWRITE_COLLECTION_HERO_BANNERS
ENV VITE_APPWRITE_BANNERS_BUCKET_ID=$VITE_APPWRITE_BANNERS_BUCKET_ID
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
ENV VITE_APPWRITE_COLLECTION_BANK_ACCOUNTS=$VITE_APPWRITE_COLLECTION_BANK_ACCOUNTS
ENV VITE_APPWRITE_COLLECTION_PAYOUT_REQUESTS=$VITE_APPWRITE_COLLECTION_PAYOUT_REQUESTS

RUN npm run build
RUN cd dist/server && ln -sf index.js server.js

EXPOSE 80
CMD ["npm", "run", "preview", "--", "--port", "80", "--host", "0.0.0.0"]
