version: "3.8"

services:
  coolpool-frontend:
    build: .
    container_name: coolpool-frontend
    restart: unless-stopped
    networks:
      - coolify
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coolpool.rule=Host(`coolpool.in`) || Host(`www.coolpool.in`)"
      - "traefik.http.routers.coolpool.entrypoints=web,websecure"
      - "traefik.http.services.coolpool.loadbalancer.server.port=80"
      - "traefik.http.routers.coolpool.tls=true"
      - "traefik.http.routers.coolpool.tls.certresolver=letsencrypt"

networks:
  coolify:
    external: true
