/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HostRouteImport } from './routes/host'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DriverOnboardingRouteImport } from './routes/driver/onboarding'
import { Route as DriverLoginRouteImport } from './routes/driver/login'
import { Route as DriverDashboardRouteImport } from './routes/driver/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOnboardingRoute = DriverOnboardingRouteImport.update({
  id: '/driver/onboarding',
  path: '/driver/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver/login',
  path: '/driver/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver/dashboard',
  path: '/driver/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/host': typeof HostRoute
  '/how-it-works': typeof HowItWorksRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/onboarding': typeof DriverOnboardingRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/host': typeof HostRoute
  '/how-it-works': typeof HowItWorksRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/onboarding': typeof DriverOnboardingRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/host': typeof HostRoute
  '/how-it-works': typeof HowItWorksRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/onboarding': typeof DriverOnboardingRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/host'
    | '/how-it-works'
    | '/search'
    | '/trips'
    | '/admin/dashboard'
    | '/driver/dashboard'
    | '/driver/login'
    | '/driver/onboarding'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/host'
    | '/how-it-works'
    | '/search'
    | '/trips'
    | '/admin/dashboard'
    | '/driver/dashboard'
    | '/driver/login'
    | '/driver/onboarding'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/host'
    | '/how-it-works'
    | '/search'
    | '/trips'
    | '/admin/dashboard'
    | '/driver/dashboard'
    | '/driver/login'
    | '/driver/onboarding'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HostRoute: typeof HostRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SearchRoute: typeof SearchRoute
  TripsRoute: typeof TripsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverOnboardingRoute: typeof DriverOnboardingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/onboarding': {
      id: '/driver/onboarding'
      path: '/driver/onboarding'
      fullPath: '/driver/onboarding'
      preLoaderRoute: typeof DriverOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/driver/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/driver/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HostRoute: HostRoute,
  HowItWorksRoute: HowItWorksRoute,
  SearchRoute: SearchRoute,
  TripsRoute: TripsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverOnboardingRoute: DriverOnboardingRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
